### ISSUE TITLE
bug list déroulé

### ISSUE THREAD

**Issue by ethiansjh** [souryvath/ng-covid-19#1]
bonjour 
j'utilise tous les jours votre application mais aujourd'hui je vois que des numéros à la places de noms de pays.

Merci de corriger : )

**Comment by souryvath** [comment]
Hello, j'ai fait un update du site ici : https://www.cascoronavirus.fr/

**Comment by ethiansjh** [comment]
merci !

vous pouvez ajouter un map monde ?

**Comment by ethiansjh** [comment]
https://www.elastic.co/fr/maps

un example 👍

**Comment by souryvath** [comment]
Résolu avec la nouvelle version du site : https://www.cascoronavirus.fr/
